"""Static sequence vectors copied from published records."""

# Homo sapiens HBB CDS, GenBank NM_000518.5, coordinates 51..494.
HBB_CDS = (
    "ATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTG"
    "AGGCCCTGGGCAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTCCACTCCTG"
    "ATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGATGGCCTGGCTCACCT"
    "GGACAACCTCAAGGGCACCTTTGCCACACTGAGTGAGCTGCACTGTGACAAGCTGCACGTGGATCCTGAGAACTTCAGG"
    "CTCCTGGGCAACGTGCTGGTCTGTGTGCTGGCCCATCACTTTGGCAAAGAATTCACCCCACCAGTGCAGGCTGCCTATCA"
    "GAAAGTGGTGGCTGGTGTGGCTAATGCCCTGGCCCACAAGTATCACTAA"
)

# M13 forward (-21) primer, Messing (1983), Methods Enzymol. 101:20-78.
M13_FORWARD = "TGTAAAACGACGGCCAGT"
M13_REVERSE_COMPLEMENT = "ACTGGCCGTCGTTTTACA"

# NCBI/Biopython genetic-code documentation example.
NCBI_TRANSLATION_SEQUENCE = "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"
NCBI_TRANSLATION_PROTEIN = "MAIVMGR*KGAR*"
